/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import Entities.Sessao;
import Utils.Arquivo;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author laboratorio
 */
public class InterfaceTelefonica extends javax.swing.JFrame {
    
    private HashMap<String, Sessao> sessoes;
    

    /**
     * Creates new form Interface
     */
    public InterfaceTelefonica() {
        initComponents();
        sessoes = new HashMap<>();  //Inicializa o HashMap
        lbl_numerosCarregados.setText("0");     //Inicializa o label direto com 0 registro telefonico
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_numerosCarregados = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        jLabel3 = new javax.swing.JLabel();
        txt_numero = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_resultados = new javax.swing.JTextArea();
        btn_carregarArquivo = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("SISTEMA DE CONSULTA DE SESSÕES TELEFONICAS");

        jLabel2.setText("Nº de Registros encontrados no sistema:");

        lbl_numerosCarregados.setText("jLabel3");

        jLabel3.setText("Número de celular:");

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado da consulta:");

        txtA_resultados.setColumns(20);
        txtA_resultados.setRows(5);
        jScrollPane1.setViewportView(txtA_resultados);

        btn_carregarArquivo.setText("Carregar Arquivo");
        btn_carregarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carregarArquivoActionPerformed(evt);
            }
        });

        btn_sair.setText("SAIR");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(316, 316, 316))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_numerosCarregados))
                                .addComponent(jLabel4)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(262, 262, 262)
                            .addComponent(btn_buscar)
                            .addGap(59, 59, 59)
                            .addComponent(btn_limpar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_carregarArquivo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sair))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_numerosCarregados))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpar)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_carregarArquivo)
                    .addComponent(btn_sair))
                .addGap(148, 148, 148))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String numeroCelular = txt_numero.getText().trim();
        
        //requestFocus é muto brabo, ele já coloca o cursor ja no campo, sem o usuário precisar clicar
        if(numeroCelular.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor digite um número de celular!", "campo vazio", JOptionPane.WARNING_MESSAGE);
            txt_numero.requestFocus();
            return;
        }
        
        if(sessoes.isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhuma sessão carregada!\nPor favor, carregue um arquivo primeiro..", "Lista vazia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Sessao sessaoEncontrada = sessoes.get(numeroCelular);
        
        if (sessaoEncontrada != null) {
            //Formata os dados para exibição
            String resultado = "[OK] SESSÃO ENCONTRADA\n";
            resultado += "=========================================\n\n";
            resultado += "Número de Celular: " + sessaoEncontrada.numeroCelular + "\n\n";
            resultado += "Dados da Sessão:\n";
            resultado += formatarJSON(sessaoEncontrada.dadosSessao);
            
            txtA_resultados.setText(resultado);
        } else {
            String resultado = "[FALHA] SESSÃO NÃO ENCONTRADA\n\n";
            resultado += "O número " + numeroCelular + " não foi encontrado na base de dados.\n";
            resultado += "Verifique se o número está correto e tente novamente.";
            
            txtA_resultados.setText(resultado);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private String formatarJSON(String json){
        // Remove chaves do início e fim
        json = json.trim();
        if (json.startsWith("{")) {
            json = json.substring(1);
        }
        if (json.endsWith("}")) {
            json = json.substring(0, json.length() - 1);
        }
    
        // Separa por vírgulas e formata cada campo
        String[] campos = json.split(",(?=\\\"[^\\\"]*\\\":)");
        StringBuilder resultado = new StringBuilder();
        
        for (String campo : campos) {
            campo = campo.trim();
            // Separa chave e valor
            if (campo.contains(":")) {
                String[] partes = campo.split(":", 2);
                String chave = partes[0].replace("\"", "").trim();
                String valor = partes[1].trim();
                
                // Formata a linha
                resultado.append(String.format("%-15s : %s\n", chave, valor));
            }
        }
        
        return resultado.toString();
    }
    
    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        txt_numero.setText("");
        txtA_resultados.setText("");
        txt_numero.requestFocus();
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_carregarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carregarArquivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecione o arquivo de sessões");
        
        // Filtro para arquivos .txt
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Arquivos de texto (*.txt)", "txt"
        );
        fileChooser.setFileFilter(filter);
        
        int resultado = fileChooser.showOpenDialog(this);
        
        if (resultado == JFileChooser.APPROVE_OPTION) {
            String caminho = fileChooser.getSelectedFile().getAbsolutePath();
            
            try {
                // Limpa sessões anteriores
                sessoes.clear();
                
                // Carrega o arquivo usando a classe Arquivo
                Arquivo.carregarArquivo(sessoes, caminho);
                
                // Atualiza o contador de registros
                lbl_numerosCarregados.setText(String.valueOf(sessoes.size()));
                
                // Mensagem de sucesso
                JOptionPane.showMessageDialog(
                    this, "Arquivo carregado com sucesso!\n" + sessoes.size() + " registros foram importados.",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE
                );
                
                // Limpa os campos
                txt_numero.setText("");
                txtA_resultados.setText("");
                txt_numero.requestFocus();
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(
                    this,
                    "Erro ao carregar o arquivo:\n" + ex.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btn_carregarArquivoActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente sair do sistema?", "Confirmação",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (opcao == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Encerrando o sistema... ", "Saindo", JOptionPane.INFORMATION_MESSAGE);

            dispose(); //fecha a janela
            System.exit(0); //encerra o programa com segurança
        }
    }//GEN-LAST:event_btn_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceTelefonica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceTelefonica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_carregarArquivo;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_sair;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_numerosCarregados;
    private javax.swing.JTextArea txtA_resultados;
    private javax.swing.JTextField txt_numero;
    // End of variables declaration//GEN-END:variables
}
